### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by edba2000** [jake-b/iPod-HiFi-Tweeters#1]
Hi, the images are not available. Could you please re-upload?

**Comment by jake-b** [comment]
Images are in another branch
https://github.com/jake-b/iPod-HiFi-Tweeters/tree/assets
Thanks for your interest.

**Comment by edba2000** [comment]
Thanks!!

Cumprimentos | Best Regards

Edgar Delgado Barbosa
***@***.******@***.***>


________________________________
"Se continuares a fazer o que sempre fizeste, obterás sempre os resultados que sempre obtiveste." | "If you keep on doing what you've always done, you'll keep on getting what you've always got." ,W. L. Bateman

Por favor, pense no meio ambiente antes de imprimir este e-mail. | Please consider our environment before printing this e-mail.
Este e-mail (incluindo quaisquer arquivos anexos) é confidencial. Se recebeu este e-mail por engano, por favor, notifique o remetente imediatamente, respondendo a este e-mail e apague todas as cópias desta mensagem e anexos. | This e-mail (including any attachments) is confidential. If you have received this e-mail in error, please notify the sender immediately by return e-mail and delete all copies of this message and any attachments.
________________________________
